# Generated by Django 5.1.7 on 2025-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Author',
            field=models.CharField(default='Unknown_User', max_length=75),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='ingredients'),
        ),
    ]
