# Generated by Django 5.1.7 on 2025-03-23 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_author_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Author',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=models.TextField(default='Directions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='ingredients:'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='recipes.category')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='recipes.subcategory'),
        ),
    ]
