# Generated by Django 5.1.7 on 2025-03-19 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_category_alter_recipe_body_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subcategories',
            field=models.ManyToManyField(blank=True, default='0', related_name='posts', to='recipes.subcategory'),
        ),
    ]
