# Generated by Django 5.1.7 on 2025-03-19 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_category_alter_recipe_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='recipes.subcategory'),
        ),
    ]
