# Generated by Django 5.1.7 on 2025-03-19 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_category_alter_recipe_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name2',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='recipes.category'),
        ),
    ]
